import KnockoutMatch from "./KnockoutMatch";

export default function KnockoutStage() {
  return (
    <div className="flex gap-6">
      <div className="flex flex-col justify-around gap-3">
        
      </div>
      <div className="flex flex-col justify-around gap-3">
        <KnockoutMatch
          leftLine={false}
          rightLine={true}
          rightConnectingLine={true}
          leftConnectingLine={false}
          connectingLineHeight="h-28"
        />
        <KnockoutMatch
          leftLine={false}
          rightLine={true}
          rightConnectingLine={false}
          leftConnectingLine={false}
          connectingLineHeight="h-28"
        />
        <KnockoutMatch
          leftLine={false}
          rightLine={true}
          rightConnectingLine={true}
          leftConnectingLine={false}
          connectingLineHeight="h-28"
        />
        <KnockoutMatch
          leftLine={false}
          rightLine={true}
          rightConnectingLine={false}
          leftConnectingLine={false}
          connectingLineHeight="h-28"
        />
        <KnockoutMatch
          leftLine={false}
          rightLine={true}
          rightConnectingLine={true}
          leftConnectingLine={false}
          connectingLineHeight="h-28"
        />
        <KnockoutMatch
          leftLine={false}
          rightLine={true}
          rightConnectingLine={false}
          leftConnectingLine={false}
          connectingLineHeight="h-28"
        />
        <KnockoutMatch
          leftLine={false}
          rightLine={true}
          rightConnectingLine={true}
          leftConnectingLine={false}
          connectingLineHeight="h-28"
        />
        <KnockoutMatch
          leftLine={false}
          rightLine={true}
          rightConnectingLine={false}
          leftConnectingLine={false}
          connectingLineHeight="h-28"
        />
      </div>
      <div className="flex flex-1 flex-col justify-around">
        <KnockoutMatch
          leftLine={true}
          rightLine={true}
          rightConnectingLine={true}
          leftConnectingLine={false}
          connectingLineHeight="h-55"
        />
        <KnockoutMatch
          leftLine={true}
          rightLine={true}
          rightConnectingLine={false}
          leftConnectingLine={false}
          connectingLineHeight="h-28"
        />
        <KnockoutMatch
          leftLine={true}
          rightLine={true}
          rightConnectingLine={true}
          leftConnectingLine={false}
          connectingLineHeight="h-55"
        />
        <KnockoutMatch
          leftLine={true}
          rightLine={true}
          rightConnectingLine={false}
          leftConnectingLine={false}
          connectingLineHeight="h-28"
        />
      </div>
      <div className="flex flex-1 flex-col justify-around">
        <KnockoutMatch
          leftLine={true}
          rightLine={true}
          rightConnectingLine={true}
          leftConnectingLine={false}
          connectingLineHeight="h-109.5"
        />
        <KnockoutMatch
          leftLine={true}
          rightLine={true}
          rightConnectingLine={false}
          leftConnectingLine={false}
          connectingLineHeight="h-55"
        />
      </div>
      <div className="flex flex-1 flex-col justify-around">
        <KnockoutMatch
          leftLine={true}
          rightLine={true}
          rightConnectingLine={true}
          leftConnectingLine={false}
          connectingLineHeight="h-60"
        />
      </div>
      <div className="relative flex flex-1 flex-col justify-around">
        <KnockoutMatch
          leftLine={true}
          rightLine={true}
          rightConnectingLine={true}
          leftConnectingLine={false}
          connectingLineHeight="h-60"
        />
        <div className="absolute w-full top-156.75">
          <KnockoutMatch
            leftLine={true}
            rightLine={true}
            rightConnectingLine={false}
            leftConnectingLine={false}
            connectingLineHeight="h-109.5"
          />
        </div>
      </div>
      <div className="relative flex flex-1 flex-col justify-around">
        <KnockoutMatch
          leftLine={true}
          rightLine={true}
          rightConnectingLine={false}
          leftConnectingLine={false}
          connectingLineHeight="h-60"
        />
      </div>
      <div className="flex flex-1 flex-col justify-around">
        <KnockoutMatch
          leftLine={true}
          rightLine={true}
          rightConnectingLine={false}
          leftConnectingLine={true}
          connectingLineHeight="h-109.5"
        />
        <KnockoutMatch
          leftLine={true}
          rightLine={true}
          rightConnectingLine={false}
          leftConnectingLine={false}
          connectingLineHeight="h-55"
        />
      </div>
      <div className="flex flex-1 flex-col justify-around">
        <KnockoutMatch
          leftLine={true}
          rightLine={true}
          rightConnectingLine={false}
          leftConnectingLine={true}
          connectingLineHeight="h-55"
        />
        <KnockoutMatch
          leftLine={true}
          rightLine={true}
          rightConnectingLine={false}
          leftConnectingLine={false}
          connectingLineHeight="h-28"
        />
        <KnockoutMatch
          leftLine={true}
          rightLine={true}
          rightConnectingLine={false}
          leftConnectingLine={true}
          connectingLineHeight="h-55"
        />
        <KnockoutMatch
          leftLine={true}
          rightLine={true}
          rightConnectingLine={false}
          leftConnectingLine={false}
          connectingLineHeight="h-28"
        />
      </div>
      <div className="flex flex-1 flex-col justify-around gap-3">
        <KnockoutMatch
          leftLine={true}
          rightLine={false}
          rightConnectingLine={false}
          leftConnectingLine={true}
          connectingLineHeight="h-28"
        />
        <KnockoutMatch
          leftLine={true}
          rightLine={false}
          rightConnectingLine={false}
          leftConnectingLine={false}
          connectingLineHeight="h-28"
        />
        <KnockoutMatch
          leftLine={true}
          rightLine={false}
          rightConnectingLine={false}
          leftConnectingLine={true}
          connectingLineHeight="h-28"
        />
        <KnockoutMatch
          leftLine={true}
          rightLine={false}
          rightConnectingLine={false}
          leftConnectingLine={false}
          connectingLineHeight="h-28"
        />
        <KnockoutMatch
          leftLine={true}
          rightLine={false}
          rightConnectingLine={false}
          leftConnectingLine={true}
          connectingLineHeight="h-28"
        />
        <KnockoutMatch
          leftLine={true}
          rightLine={false}
          rightConnectingLine={false}
          leftConnectingLine={false}
          connectingLineHeight="h-28"
        />
        <KnockoutMatch
          leftLine={true}
          rightLine={false}
          rightConnectingLine={false}
          leftConnectingLine={true}
          connectingLineHeight="h-28"
        />
        <KnockoutMatch
          leftLine={true}
          rightLine={false}
          rightConnectingLine={false}
          leftConnectingLine={false}
          connectingLineHeight="h-28"
        />
      </div>
    </div>
  );
}